### ISSUE TITLE
Change issue author (if possible) when a pull is attached

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic/git-hub#122]
When an author of a pull request attaches code to an issue which was filed by someone else, the github notification will list the author of the issue as the opener of the PR. E.g.:

```
(I'm the author of the PR, although Mathias is the author of the issue)

mathias-baumann-sociomantic opened pull request sociomantic/coral#56 
```

I think this could be fixed by making the git hub tool change the author of the issue before committing the code (if this is possible).

Otherwise this may just be a Github issue (but you know it takes ages for them to fix these kinds of things).

**Comment by leandro-lucarella-sociomantic** [comment]
Sadly there is no way to change an issue/PR author using the GitHub API, so we can't fix this. Closing as invalid, sorry!

**Comment by andrej-mitrovic-sociomantic** [comment]
But, my glorious GitHub stats..!!

:P That's ok, at least it's not a bug from our side.
