### ISSUE TITLE
git hub pull show shows old diff

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic/git-hub#123]
If a PR was modified after creation, `git hub pull show` will still show the outdated diff.

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, we are very dumb when retrieving stuff, my first guess is it could be a GitHub's bug. But I should check.

**Comment by leandro-lucarella-sociomantic** [comment]
Is this still an issue, are you able to reproduce this?

**Comment by leandro-lucarella-sociomantic** [comment]
Closing due to lack of feedback. Feel free to reopen if this is still an issue.
