### ISSUE TITLE
Provide option to name the fork of a repository when cloning

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic/git-hub#127]
Currently `git-hub` has the `--remote` flag to name the `upstream` (the blessed) repo. But there's no equivalent to naming the user's fork of the repo, which defaults to `origin`.

The problem with the name `origin` is that inside of submodules `origin` is actually equivalent to the meaning of `upstream`. This makes it easy to create the mistake of pushing to `origin` while inside of a submodule, when we wanted to push to our fork instead. To visualize:

```
$ git hug clone sociomantic/repo
$ cd repo
$ git submodule update --init
$ git remote -v

origin	git@github.com:andrej-mitrovic-sociomantic/repo.git (fetch)
origin	git@github.com:andrej-mitrovic-sociomantic/repo.git (push)
upstream	git@github.com:sociomantic/repo.git (fetch)
upstream	git@github.com:sociomantic/repo.git (push)

$ cd submodules/repo2
$ git remote -v

origin	git@github.com:sociomantic/repo2.git (fetch)
origin	git@github.com:sociomantic/repo2.git (push)
```

If we had the option to name our fork during cloning, we could never make the mistake of pushing to the blessed repo. I'd make all my scripts or aliases always refer to my fork name (e.g. `drey` instead of `origin`), and a force push would never break a blessed repo this way.

**Comment by andrej-mitrovic-sociomantic** [comment]
Edit: To elaborate why you would sometimes want to push a change that you did inside of an actual submodule (but to your own fork). Continuing from the former example:

```
$ cd submodules/ocean
$ git remote -v

origin  git@github.com:sociomantic/ocean.git (fetch)
origin  git@github.com:sociomantic/ocean.git (push)
drey    git@github.com:andrej-mitrovic-sociomantic/ocean.git (fetch)
drey    git@github.com:andrej-mitrovic-sociomantic/ocean.git (push)

$ git checkout -b some-ocean-fix
$ git add ...
$ git commit -m "Fix wrong return value in foobar"
$ git push drey
> Proceed to make a pull request for ocean.
```

Note that if I did `git push origin` above this would have been a mistake, as origin points to the blessed repo.

**Comment by mihails-strasuns-sociomantic** [comment]
I'd love to have a special flag to `git hub clone` that sets remotes in submodules same way as in root repo.

**Comment by leandro-lucarella-sociomantic** [comment]
> I'd love to have a special flag to git hub clone that sets remotes in submodules same way as in root repo.

Add a new issue for that, this issue should be super easy to implement, what you suggest might be a bit more work (although not particularly difficult, I guess).

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic/git-hub/issues/128

**Comment by leandro-lucarella-sociomantic** [comment]
This is actually already supported.

From the [man page](https://github.com/sociomantic/git-hub/blob/master/man.rst#commands):

```
GIT CLONE OPTIONS
    Any standard git clone option can be passed. Not all of them might make sense when cloning a GitHub repo to be used with this tool though.
```

From the [git clone man page](https://www.kernel.org/pub/software/scm/git/docs/git-clone.html):

```
       --origin <name>, -o <name>
           Instead of using the remote name origin to keep track of the
           upstream repository, use <name>.
```

Maybe it's bit obscure to find it easily, but wanting to change the name origin is not a very common operation, so I think it's fine.
