### ISSUE TITLE
Allow setting up with existing access token

### ISSUE THREAD

**Issue by Cloudef** [sociomantic/git-hub#150]
I have two computers, and I don't want to revoke my old token. I know this is possible with git config manually, but would be nice to have git hub setup option for it.

**Comment by mihails-strasuns-sociomantic** [comment]
With latest `git-hub` release it should ask you for a new name for a token as an alternative for revoking, which will result in different tokens for different machines (working simultaneously).

AFAIR it was reusing the same token before but some GitHub API change made it hard/impossible.

**Comment by Cloudef** [comment]
Ah right, it does indeed. Thank you.

**Comment by mihails-strasuns-sociomantic** [comment]
You're welcome.
