### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic/git-hub#162]
```
Error: Can't start a pull rebase while a regular reabase is in progress
```

`reabase` => `rebase`.

Also it would be nice if it said we can use `git rebase --abort` in this case.

**Comment by llucax** [comment]
No PR? :blush: 

And about the `git rebase --abort` suggestion, I'm not sure the tool should do that, that's only true if you want to abort the current rebase, but there might be many cases where you don't (you want to finish it). I'm not very sure about giving advice in the tool to do something that can potentially make the user lose work. And explaining all this might be too much for an error message, it is expected that the user knows how to use git.

**Comment by andrej-mitrovic-sociomantic** [comment]
PR coming tomorrow!



On Wed, Nov 11, 2015 at 2:07 PM -0800, "Leandro Lucarella" <notifications@github.com<mailto:notifications@github.com>> wrote:


No PR? [:blush:]

And about the git rebase --abort suggestion, I'm not sure the tool should do that, that's only true if you want to abort the current rebase, but there might be many cases where you don't (you want to finish it). I'm not very sure about giving advice in the tool to do something that can potentially make the user lose work. And explaining all this might be too much for an error message, it is expected that the user knows how to use git.

-

**Comment by andrej-mitrovic-sociomantic** [comment]
This appears to be fixed.

**Comment by leandro-lucarella-sociomantic** [comment]
Thank @jwilk (bed04738ababb4e327e6c209d683f44dab298136).
