### ISSUE TITLE
Clone sometimes fails because it tries to clone the fork before the fork was actually completed

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic/git-hub#37]
GitHub takes some time to complete the fork after it was requested through the API, the API call is not blocked until the fork is completed, so when we try to clone the just forked repository, github complaints with weird error messages.

It would be good to investigate if there is an easy way to find out if a fork was completed, and poll github until that happens before continuing with the actual cloning.

**Comment by mathias-baumann-sociomantic** [comment]
Is this this error?

```
➜  git hub clone git@github.com:sociomantic/git-hub                                             
Forking git@github.com:sociomantic/git-hub to mathias-baumann-sociomantic/git-hub
Error: GitHub error: Not Found
```

Trying to clone without having a fork here.

**Comment by leandro-lucarella-sociomantic** [comment]
Probably, if you do it again ad it succeeds, then it probably was that...

**Comment by mathias-baumann-sociomantic** [comment]
Nope, doing it again just fails again. Tried it a few times now.

**Comment by leandro-lucarella-sociomantic** [comment]
With the exact same message? It tries to fork over and over again? Was the fork ever done in GitHub?
Also, can you provide the output of `git hub -v clone git@github.com:sociomantic/git-hub`?

**Comment by mathias-baumann-sociomantic** [comment]
Always the same message. Yes I can provide that output, but the file is about 325kb big..

**Comment by mathias-baumann-sociomantic** [comment]
And no, the fork was never done.

**Comment by leandro-lucarella-sociomantic** [comment]
> but the file is about 325kb big

Which file?

**Comment by mathias-baumann-sociomantic** [comment]
The file containing the output of that command :P

**Comment by leandro-lucarella-sociomantic** [comment]
That's not normal, but I just spotted the problem. You are using the URL to specify the repo, you have to specify `user/repo` only (RTFM :stuck_out_tongue_closed_eyes: )

**Comment by leandro-lucarella-sociomantic** [comment]
OK, feel free to open an issue about improving the error message, or supporting URLs, or whatever....

**Comment by mathias-baumann-sociomantic** [comment]
I  tried that too and it resulted in the same error... but doing it now seems to work. Odd.
